/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jpmp_manager_DeviceManager */

#ifndef _Included_jpmp_manager_DeviceManager
#define _Included_jpmp_manager_DeviceManager
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: _instance */
/*
 * Class:     jpmp_manager_DeviceManager
 * Method:    createInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jpmp_manager_DeviceManager_createInstance
  (JNIEnv *, jobject);

/*
 * Class:     jpmp_manager_DeviceManager
 * Method:    releaseInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jpmp_manager_DeviceManager_releaseInstance
  (JNIEnv *, jobject);

/*
 * Class:     jpmp_manager_DeviceManager
 * Method:    setVerbose
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_jpmp_manager_DeviceManager_setVerbose
  (JNIEnv *, jobject, jint);

/*
 * Class:     jpmp_manager_DeviceManager
 * Method:    detectDevices
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jpmp_manager_DeviceManager_detectDevices
  (JNIEnv *, jobject);

/*
 * Class:     jpmp_manager_DeviceManager
 * Method:    checkDevice
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jpmp_manager_DeviceManager_checkDevice
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jpmp_manager_DeviceManager
 * Method:    releaseDevice
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jpmp_manager_DeviceManager_releaseDevice
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
