/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jpmp_device_UsbDevice */

#ifndef _Included_jpmp_device_UsbDevice
#define _Included_jpmp_device_UsbDevice
#ifdef __cplusplus
extern "C" {
#endif
#undef jpmp_device_UsbDevice_USB_MODE_CONNECTED
#define jpmp_device_UsbDevice_USB_MODE_CONNECTED 0L
#undef jpmp_device_UsbDevice_USB_MODE_MSC
#define jpmp_device_UsbDevice_USB_MODE_MSC 1L
#undef jpmp_device_UsbDevice_USB_MODE_MTP
#define jpmp_device_UsbDevice_USB_MODE_MTP 2L
#undef jpmp_device_UsbDevice_ERROR_SUCCESS
#define jpmp_device_UsbDevice_ERROR_SUCCESS 0LL
#undef jpmp_device_UsbDevice_ERROR_UNKNOWN_DEVICE
#define jpmp_device_UsbDevice_ERROR_UNKNOWN_DEVICE 1LL
#undef jpmp_device_UsbDevice_ERROR_FILE_NOTFOUND
#define jpmp_device_UsbDevice_ERROR_FILE_NOTFOUND 2LL
#undef jpmp_device_UsbDevice_ERROR_FOLDER_NOTFOUND
#define jpmp_device_UsbDevice_ERROR_FOLDER_NOTFOUND 3LL
#undef jpmp_device_UsbDevice_ERROR_FOLDER_NOTEMPTY
#define jpmp_device_UsbDevice_ERROR_FOLDER_NOTEMPTY 4LL
#undef jpmp_device_UsbDevice_ERROR_METADATA_PROPERTY
#define jpmp_device_UsbDevice_ERROR_METADATA_PROPERTY 5LL
#undef jpmp_device_UsbDevice_ERROR_INVOKE_METHOD
#define jpmp_device_UsbDevice_ERROR_INVOKE_METHOD 6LL
#undef jpmp_device_UsbDevice_ERROR_INIT_DEViCEMANAGER
#define jpmp_device_UsbDevice_ERROR_INIT_DEViCEMANAGER 7LL
#undef jpmp_device_UsbDevice_ERROR_DEVICE_NOTMOUNTED
#define jpmp_device_UsbDevice_ERROR_DEVICE_NOTMOUNTED 8LL
#undef jpmp_device_UsbDevice_ERROR_PATH_EXISTS
#define jpmp_device_UsbDevice_ERROR_PATH_EXISTS 9LL
#undef jpmp_device_UsbDevice_ERROR_MTP_NOTAVAILABLE
#define jpmp_device_UsbDevice_ERROR_MTP_NOTAVAILABLE 10LL
#undef jpmp_device_UsbDevice_ERROR_MSC_NOTAVAILABLE
#define jpmp_device_UsbDevice_ERROR_MSC_NOTAVAILABLE 11LL
#undef jpmp_device_UsbDevice_ERROR_WRONG_PARAMETER
#define jpmp_device_UsbDevice_ERROR_WRONG_PARAMETER 12LL
#undef jpmp_device_UsbDevice_ERROR_UNKNOWN
#define jpmp_device_UsbDevice_ERROR_UNKNOWN 1000LL
#undef jpmp_device_UsbDevice_ERROR_NOTIMPL
#define jpmp_device_UsbDevice_ERROR_NOTIMPL 2000LL
/*
 * Class:     jpmp_device_UsbDevice
 * Method:    existFile
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jpmp_device_UsbDevice_existFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jpmp_device_UsbDevice
 * Method:    deleteFile
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jpmp_device_UsbDevice_deleteFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jpmp_device_UsbDevice
 * Method:    existFolder
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jpmp_device_UsbDevice_existFolder
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jpmp_device_UsbDevice
 * Method:    deleteFolder
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jpmp_device_UsbDevice_deleteFolder
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jpmp_device_UsbDevice
 * Method:    createFolder
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jpmp_device_UsbDevice_createFolder
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jpmp_device_UsbDevice
 * Method:    getMetadata
 * Signature: (Ljava/lang/String;Ljpmp/device/FileMetadata;)J
 */
JNIEXPORT jlong JNICALL Java_jpmp_device_UsbDevice_getMetadata
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     jpmp_device_UsbDevice
 * Method:    updateMetadata
 * Signature: (Ljava/lang/String;Ljpmp/device/FileMetadata;)J
 */
JNIEXPORT jlong JNICALL Java_jpmp_device_UsbDevice_updateMetadata
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     jpmp_device_UsbDevice
 * Method:    getFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljpmp/notifier/IDeviceTransferNotifier;)J
 */
JNIEXPORT jlong JNICALL Java_jpmp_device_UsbDevice_getFile
  (JNIEnv *, jobject, jstring, jstring, jobject);

/*
 * Class:     jpmp_device_UsbDevice
 * Method:    sendFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljpmp/notifier/IDeviceTransferNotifier;Ljpmp/device/FileMetadata;)J
 */
JNIEXPORT jlong JNICALL Java_jpmp_device_UsbDevice_sendFile
  (JNIEnv *, jobject, jstring, jstring, jobject, jobject);

/*
 * Class:     jpmp_device_UsbDevice
 * Method:    parseFolder
 * Signature: (Ljava/lang/String;Ljpmp/notifier/IParseTreeNotifier;)J
 */
JNIEXPORT jlong JNICALL Java_jpmp_device_UsbDevice_parseFolder
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
